import picOne from "../assets/15781s.jpg";
import picTwo from "../assets/16598s.jpg";
import picThree from "../assets/16675s.jpg";
import picFour from "../assets/16733s.jpg";



export const links = [
    {
        name: "O klubu",
        hash: "About",
    },
    {
        name: "Chodský pes",
        hash: "Bohemian-shepherd",
    },
    {
        name: "Chovatelství",
        hash: "Pedigree",
    },
    {
        name: "Galerie",
        hash: "Gallery",
    },
    {
        name: "Kontakt",
        hash: "Contact",
    },
]

export const standardOfDog = [
    {
        headline: "Země původu",
        text: "Česká republika",
    },
    {
        headline: "Datum publikace platného původního standardu",
        text: "28.10.1984",
    },
    {
        headline: "Použití",
        text: "Všestranně pracovní pes",
    },
    {
        headline: "Stručný historický přehled",
        text: "Původ tohoto plemene je historický. Spisovatel Jindř. Šimon Baar popisoval ve svých díléch opěvujících Chodsko (v letech 1923-1924) psy z oblasti Šumavy, které nazýval chodské. Tito typově vyrovnaní a velmi houževnatí psi měli za úkol střežit zemské stezky, bránit majetek svých pánů, pomáhali při pasení. S historií Chodska ve své písemnosi o Chodsku z r. 1864 psal o tamním lidu s přezdívkou Psohlavci z důvodu, že měli na svém praporci jako znamení věrného strážce domu.",
    },
    {
        headline: "Celková charakteristika",
        text: "Středně velký pes ovčáckého typu s obdélníkovým rámcem těla. Má dlouhou srst s bohatou podsadou, která ho činí otužilým a odolným vůči povětrnostním vlivům. Vyniká harmonickou stavbou těla. Všechny tělesné partie jsou sladěny tak, že jako celek působí kompaktně a ladně. Charakteristické pro plemeno je postavení a nesení krátkých uší, elegantní linie dlouhé šíje a krku a dále bohatost dlouhé srsti. Jeho pohyb je lehký a volný. Celkový tvar těla od hlavy až po ocas je tvořen souborem ladných křivek.",
    },
    {
        headline: "Chování a povaha",
        text: "Temperamentní pes rychlých, ne však překotných reakcí. Lehce učenlivý, pozorný, dobře ovladatelný, poddajný. Je skromný, nenáročný a houževnatý, je milujícím členem rodiny. Je nebojácný, pevných nervů a mimořádně ostražitý. Má výborné čichové schopnosti. Pro plemeno je typický temperament bez známek nervozity.",
    },
]

export const pedigreeDog = [
    {
        station: "Bea Deli",
        breeder: "Nejepsová Magdaléna",
        mother: "Deli Matomico",
        father: "Fresh Prince Lukato Gold",
        dateOfBirth: "16.8.2024",
        numOfDogs: "3",
        numOFFogs: "3",
        comment: "",
        imgOfDog: picOne,
        imgOfFog: picTwo,
    },
    {
        station: "pod Všebrubskou skálou",
        breeder: "Šimková Mirka",
        mother: "Agree Lucky",
        father: "Ozzy z Letinské Kovárny",
        dateOfBirth: "16.8.2024",
        numOfDogs: "1",
        numOFFogs: "1",
        comment: "",
        imgOfDog: picThree,
        imgOfFog: picFour,
    },
    {
        station: "Goxian",
        breeder: "Nývlt Zbyněk",
        mother: "Jolly Vigilo",
        father: "Charon Vigilo",
        dateOfBirth: "15.8.2024",
        numOfDogs: "5",
        numOFFogs: "3",
        comment: "volba chovatele",
        imgOfDog: "",
        imgOfFog: "",
    },
    {
        station: "z Nových Cholupic",
        breeder: "Csolle Zdeněk",
        mother: "Bethany Amicus",
        father: "Ascot Silesia",
        dateOfBirth: "11.8.2024",
        numOfDogs: "3",
        numOFFogs: "4",
        comment: "",
        imgOfDog: "",
        imgOfFog: "",
    },
    {
        station: "ze Strážného hradu",
        breeder: "Michálková Petra",
        mother: "Tesi",
        father: "Etyen",
        dateOfBirth: "4.8.2024",
        numOfDogs: "2",
        numOFFogs: "3",
        comment: "",
        imgOfDog: "",
        imgOfFog: "",
    },
    {
        station: "od Majčina jezera",
        breeder: "Voldřichová Kateřina",
        mother: "Touha",
        father: "Dream",
        dateOfBirth: "16.8.2024",
        numOfDogs: "4",
        numOFFogs: "3",
        comment: "",
        imgOfDog: "",
        imgOfFog: "",
    },
    {
        station: "od Leskounského kopce",
        breeder: "Sobotka Pavel",
        mother: "Gesí",
        father: "Dumper",
        dateOfBirth: "23.7.2024",
        numOfDogs: "1",
        numOFFogs: "3",
        comment: "",
        imgOfDog: "",
        imgOfFog: "",
    },
    {
        station: "Daraskár",
        breeder: "Konoková Yvetta",
        mother: "Wítězka",
        father: "O-cort",
        dateOfBirth: "20.7.2024",
        numOfDogs: "2",
        numOFFogs: "5",
        comment: "",
        imgOfDog: "",
        imgOfFog: "",
    },
    {
        station: "Bea Deli",
        breeder: "Nejepsová",
        mother: "Deli Matomico",
        father: "Fresh Prince Lukato Gold",
        dateOfBirth: "16.8.2024",
        numOfDogs: "3",
        numOFFogs: "3",
        comment: "",
        imgOfDog: "",
        imgOfFog: "",
    },
    {
        station: "Bea Deli",
        breeder: "Nejepsová",
        mother: "Deli Matomico",
        father: "Fresh Prince Lukato Gold",
        dateOfBirth: "16.8.2024",
        numOfDogs: "3",
        numOFFogs: "3",
        comment: "",
        imgOfDog: "",
        imgOfFog: "",
    },
    {
        station: "Bea Deli",
        breeder: "Nejepsová",
        mother: "Deli Matomico",
        father: "Fresh Prince Lukato Gold",
        dateOfBirth: "16.8.2024",
        numOfDogs: "3",
        numOFFogs: "3",
        comment: "",
        imgOfDog: "",
        imgOfFog: "",
    },
    {
        station: "Bea Deli",
        breeder: "Nejepsová",
        mother: "Deli Matomico",
        father: "Fresh Prince Lukato Gold",
        dateOfBirth: "16.8.2024",
        numOfDogs: "3",
        numOFFogs: "3",
        comment: "",
        imgOfDog: "",
        imgOfFog: "",
    },
    {
        station: "Bea Deli",
        breeder: "Nejepsová",
        mother: "Deli Matomico",
        father: "Fresh Prince Lukato Gold",
        dateOfBirth: "16.8.2024",
        numOfDogs: "3",
        numOFFogs: "3",
        comment: "",
        imgOfDog: "",
        imgOfFog: "",
    },
    {
        station: "Bea Deli",
        breeder: "Nejepsová",
        mother: "Deli Matomico",
        father: "Fresh Prince Lukato Gold",
        dateOfBirth: "16.8.2024",
        numOfDogs: "3",
        numOFFogs: "3",
        comment: "",
        imgOfDog: "",
        imgOfFog: "",
    },
    {
        station: "Bea Deli",
        breeder: "Nejepsová",
        mother: "Deli Matomico",
        father: "Fresh Prince Lukato Gold",
        dateOfBirth: "16.8.2024",
        numOfDogs: "3",
        numOFFogs: "3",
        comment: "",
        imgOfDog: "",
        imgOfFog: "",
    },
    {
        station: "Bea Deli",
        breeder: "Nejepsová",
        mother: "Deli Matomico",
        father: "Fresh Prince Lukato Gold",
        dateOfBirth: "16.8.2024",
        numOfDogs: "3",
        numOFFogs: "3",
        comment: "",
        imgOfDog: "",
        imgOfFog: "",
    },
]